### ISSUE TITLE
Your keys are showing

### ISSUE THREAD

**Issue by evancohen** [boehm-e/gustave#1]
Hey @boehm-e just letting you know that your keys are showing:
[`system/speech_recognition/asr/ibm/index.js#L4`](https://github.com/boehm-e/gustave/blob/master/system/speech_recognition/asr/ibm/index.js#L4)

Might want to hide that to ensure that nobody takes your keys. 

Cheers!

**Comment by boehm-e** [comment]
Hey evan,

Thank you i did not notice.

Cheers


2017-05-02 2:22 GMT+02:00 Evan Cohen <notifications@github.com>:
